server:
  port: 8080
spring:
  application:
    name: "FranchiseApp"
  profiles:
    include: resilience
  h2:
    console:
      enabled: false
  r2dbc:
    initialization-mode: "never"
  sql:
    init:
      mode: "always"
      platform: "postgres"
      schema-locations: "classpath:schema.sql"
springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
adapters:
  r2dbc:
    host: "localhost"
    port: 5433
    database: "franchise_db"
    schema: "franchise_management"
    username: "user"
    password: "password"
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
      base-path: "/actuator"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
